spring:
  application:
    name: webhook-engine

  config:
    import: "optional:file:local.properties"

  datasource:
    url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5433}/${APP_DB_NAME:webhook_engine}
    username: ${APP_DB_USER}
    password: ${APP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false

  data:
    redis:
      repositories:
        enabled: false
      host: ${APP_REDIS_HOST:localhost}
      port: ${APP_REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: webhook-engine-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  flyway:
    enabled: true
    locations: classpath:db/migration

#  security:
#    api-keys: ${API_KEYS}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always